package com.outr.arango.api.model

import io.circe.Json

/**
  * AdminStatisticsGroupStruct
  *
  * @param description A description of the group.
  * @param group The identifier of the group.
  * @param name The name of the group.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class AdminStatisticsGroupStruct(description: Option[String] = None,
                                      group: Option[String] = None,
                                      name: Option[String] = None)