package com.outr.arango.api.model

import io.circe.Json

/**
  * ExplainOptions
  *
  * @param allPlans if set to *true*, all possible execution plans will be returned.
  *        The default is *false*, meaning only the optimal plan will be returned.
  * @param maxNumberOfPlans an optional maximum number of plans that the optimizer is 
  *        allowed to generate. Setting this attribute to a low value allows to put a
  *        cap on the amount of work the optimizer does.
  * @param optimizer.rules an array of to-be-included or to-be-excluded optimizer rules
  *        can be put into this attribute, telling the optimizer to include or exclude
  *        specific rules. To disable a rule, prefix its name with a `-`, to enable a rule, prefix it
  *        with a `+`. There is also a pseudo-rule `all`, which will match all optimizer rules.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class ExplainOptions(allPlans: Option[Boolean] = None,
                          maxNumberOfPlans: Option[Long] = None,
                          optimizerRules: Option[List[String]] = None)