package com.outr.arango.api.model

import io.circe.Json

/**
  * GetAdminTimeRc200
  *
  * @param error boolean flag to indicate whether an error occurred (*false* in this case)
  * @param code the HTTP status code
  * @param time The current system time as a Unix timestamp with microsecond precision of the server
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GetAdminTimeRc200(error: Boolean,
                             code: Option[Long] = None,
                             time: Option[Double] = None)