package com.outr.arango.api.model

import io.circe.Json

/**
  * PatchAPIViewPropertiesIresearch
  *
  * @param properties *** No description ***
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PatchAPIViewPropertiesIresearch(properties: Option[PostAPIViewProps] = None)