package com.outr.arango.api.model

import io.circe.Json

/**
  * PostAPIExportRestrictions
  *
  * @param fields Contains an array of attribute names to *include* or *exclude*. Matching of attribute names
  *        for *inclusion* or *exclusion* will be done on the top level only.
  *        Specifying names of nested attributes is not supported at the moment.
  * @param type has to be be set to either *include* or *exclude* depending on which you want to use
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostAPIExportRestrictions(fields: Option[List[String]] = None,
                                     `type`: Option[String] = None)