package com.outr.arango.api.model

import io.circe.Json

/**
  * PostAPIAnalyzer
  *
  * @param name The analyzer name.
  * @param features The set of features to set on the analyzer generated fields.
  *        The default value is an empty array.
  * @param properties The properties used to configure the specified type.
  *        Value may be a string, an object or null.
  *        The default value is *null*.
  * @param type The analyzer type.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostAPIAnalyzer(name: String,
                           features: Option[List[String]] = None,
                           properties: Option[String] = None,
                           `type`: Option[String] = None)