package com.outr.arango.api.model

import io.circe.Json

/**
  * PostAPIExport
  *
  * @param flush if set to *true*, a WAL flush operation will be executed prior to the
  *        export. The flush operation will start copying documents from the WAL to the
  *        collection's datafiles. There will be an additional wait time of up
  *        to *flushWait* seconds after the flush to allow the WAL collector to change
  *        the adjusted document meta-data to point into the datafiles, too.
  *        The default value is *false* (i.e. no flush) so most recently inserted or
  *        updated
  *        documents from the collection might be missing in the export.
  * @param batchSize maximum number of result documents to be transferred from
  *        the server to the client in one roundtrip (optional). If this attribute is
  *        not set, a server-controlled default value will be used.
  * @param count boolean flag that indicates whether the number of documents
  *        in the result set should be returned in the "count" attribute of the result
  *        (optional).
  *        Calculating the "count" attribute might in the future have a performance
  *        impact so this option is turned off by default, and "count" is only returned
  *        when requested.
  * @param flushWait maximum wait time in seconds after a flush operation. The default
  *        value is 10. This option only has an effect when *flush* is set to *true*.
  * @param limit an optional limit value, determining the maximum number of documents to
  *        be included in the cursor. Omitting the *limit* attribute or setting it to 0 will
  *        lead to no limit being used. If a limit is used, it is undefined which documents
  *        from the collection will be included in the export and which will be excluded. 
  *        This is because there is no natural order of documents in a collection.
  * @param restrict *** No description ***
  * @param ttl an optional time-to-live for the cursor (in seconds). The cursor will be
  *        removed on the server automatically after the specified amount of time. This
  *        is useful to ensure garbage collection of cursors that are not fully fetched
  *        by clients. If not set, a server-defined value will be used.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostAPIExport(flush: Boolean,
                         batchSize: Option[Long] = None,
                         count: Option[Boolean] = None,
                         flushWait: Option[Long] = None,
                         limit: Option[Long] = None,
                         restrict: Option[PostAPIExportRestrictions] = None,
                         ttl: Option[Long] = None)