package com.outr.arango.api.model

import io.circe.Json

/**
  * PutAPISimpleAny
  *
  * @param collection The identifier or name of the collection to query.
  *        
  *        Returns a JSON object with the document stored in the attribute
  *        *document* if the collection contains at least one document. If
  *        the collection is empty, the *document* attribute contains null.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutAPISimpleAny(collection: String)