package com.outr.arango.api.model

import io.circe.Json

/**
  * PutAPISimpleReplaceByExample
  *
  * @param collection The name of the collection to replace within.
  * @param example An example document that all collection documents are compared against.
  * @param newValue The replacement document that will get inserted in place
  *        of the "old" documents.
  * @param options *** No description ***
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutAPISimpleReplaceByExample(collection: String,
                                        example: Option[String] = None,
                                        newValue: Option[String] = None,
                                        options: Option[PutAPISimpleReplaceByExampleOptions] = None)