package com.outr.arango.api.model

import io.circe.Json

/**
  * SetofStatisticsStruct
  *
  * @param count number of values summarized
  * @param counts array containing the values
  * @param sum summarized value of all counts
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class SetofStatisticsStruct(count: Option[Int] = None,
                                 counts: Option[List[Int]] = None,
                                 sum: Option[Double] = None)