package com.outr.arango.api

/**
  * AdminEchoClientStruct
  *
  * 
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class AdminEchoClientStruct()