package com.outr.arango.api

import io.youi.client.HttpClient
          
class API(client: HttpClient) {
  val database = new APIDatabase(client)
  val view#ArangoSearch = new APIView#ArangoSearch(client)
  val analyzer = new APIAnalyzer(client)
  val collection = new APICollection(client)
  val explain = new APIExplain(client)
  val index#Geo = new APIIndex#Geo(client)
  val foxx = new APIFoxx(client)
  val index#Skiplist = new APIIndex#Skiplist(client)
  val document = new APIDocument(client)
  val index#Hash = new APIIndex#Hash(client)
  val traversal = new APITraversal(client)
  val import#Json = new APIImport#Json(client)
  val job = new APIJob(client)
  val query = new APIQuery(client)
  val index#Fulltext = new APIIndex#Fulltext(client)
  val cursor = new APICursor(client)
  val export = new APIExport(client)
  val cluster = new APICluster(client)
  val version = new APIVersion(client)
  val replication = new APIReplication(client)
  val batch = new APIBatch(client)
  val index#Persistent = new APIIndex#Persistent(client)
  val tasks = new APITasks(client)
  val index#Ttl = new APIIndex#Ttl(client)
  val queryCache = new APIQueryCache(client)
  val simple = new APISimple(client)
  val endpoint = new APIEndpoint(client)
  val view#Arangosearch = new APIView#Arangosearch(client)
  val gharial = new APIGharial(client)
  val edges = new APIEdges(client)
  val index#General = new APIIndex#General(client)
  val wal = new APIWal(client)
  val import#Document = new APIImport#Document(client)
  val transaction = new APITransaction(client)
  val aqlfunction = new APIAqlfunction(client)
  val user = new APIUser(client)
  val engine = new APIEngine(client)
  val index = new APIIndex(client)
  val view = new APIView(client)
}