package com.outr.arango.api

/**
  * CollectionFigures
  *
  * @param alive *** No description ***
  * @param compactionStatus *** No description ***
  * @param compactors *** No description ***
  * @param datafiles *** No description ***
  * @param dead *** No description ***
  * @param documentReferences The number of references to documents in datafiles that JavaScript code 
  *        currently holds. This information can be used for debugging compaction and 
  *        unload issues.
  * @param indexes *** No description ***
  * @param journals *** No description ***
  * @param lastTick The tick of the last marker that was stored in a journal
  *        of the collection. This might be 0 if the collection does not yet have
  *        a journal.
  * @param readcache *** No description ***
  * @param revisions *** No description ***
  * @param uncollectedLogfileEntries The number of markers in the write-ahead
  *        log for this collection that have not been transferred to journals or datafiles.
  * @param waitingFor An optional string value that contains information about which object type is at the 
  *        head of the collection's cleanup queue. This information can be used for debugging 
  *        compaction and unload issues.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class CollectionFigures(alive: Option[CollectionFiguresAlive] = None,
                             compactionStatus: Option[CompactionStatusAttributes] = None,
                             compactors: Option[CollectionFiguresCompactors] = None,
                             datafiles: Option[CollectionFiguresDatafiles] = None,
                             dead: Option[CollectionFiguresDead] = None,
                             documentReferences: Option[Long] = None,
                             indexes: Option[CollectionFiguresIndexes] = None,
                             journals: Option[CollectionFiguresJournals] = None,
                             lastTick: Option[Long] = None,
                             readcache: Option[CollectionFiguresReadcache] = None,
                             revisions: Option[CollectionFiguresRevisions] = None,
                             uncollectedLogfileEntries: Option[Long] = None,
                             waitingFor: Option[String] = None)