package com.outr.arango.api

/**
  * CollectionFiguresDatafiles
  *
  * @param count The number of datafiles.
  * @param fileSize The total filesize of datafiles (in bytes).
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class CollectionFiguresDatafiles(count: Option[Long] = None,
                                      fileSize: Option[Long] = None)