package com.outr.arango.api

/**
  * CollectionFiguresAlive
  *
  * @param count The number of currently active documents in all datafiles
  *        and journals of the collection. Documents that are contained in the
  *        write-ahead log only are not reported in this figure.
  * @param size The total size in bytes used by all active documents of
  *        the collection. Documents that are contained in the write-ahead log only are
  *        not reported in this figure.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class CollectionFiguresAlive(count: Option[Long] = None,
                                  size: Option[Long] = None)