package com.outr.arango.api

/**
  * CollectionFiguresReadcache
  *
  * @param count The number of revisions of this collection stored in the document revisions cache.
  * @param size The memory used for storing the revisions of this collection in the document 
  *        revisions cache (in bytes). This figure does not include the document data but 
  *        only mappings from document revision ids to cache entry locations.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class CollectionFiguresReadcache(count: Option[Long] = None,
                                      size: Option[Long] = None)