package com.outr.arango.api

/**
  * CollectionInfo
  *
  * @param keyOptions *** No description ***
  * @param doCompact Whether or not the collection will be compacted.
  *        This option is only present for the MMFiles storage engine.
  * @param globallyUniqueId Unique identifier of the collection
  * @param id unique identifier of the collection; *deprecated*
  * @param indexBuckets the number of index buckets
  *        *Only relevant for the MMFiles storage engine*
  * @param isSystem true if this is a system collection; usually *name* will start with an underscore.
  * @param isVolatile If *true* then the collection data will be
  *        kept in memory only and ArangoDB will not write or sync the data
  *        to disk. This option is only present for the MMFiles storage engine.
  * @param journalSize The maximal size setting for journals / datafiles
  *        in bytes. This option is only present for the MMFiles storage engine.
  * @param name literal name of this collection
  * @param numberOfShards The number of shards of the collection; *Cluster specific attribute.*
  * @param replicationFactor contains how many copies of each shard are kept on different DBServers.; *Cluster specific attribute.*
  * @param shardKeys contains the names of document attributes that are used to
  *        determine the target shard for documents; *Cluster specific attribute.*
  * @param shardingStrategy the sharding strategy selected for the collection; *Cluster specific attribute.*
  *        One of 'hash' or 'enterprise-hash-smart-edge'
  * @param smartGraphAttribute Attribute that is used in smart graphs, *Cluster specific attribute.*
  * @param status corrosponds to **statusString**; *Only relevant for the MMFiles storage engine*
  *          - 0: "unknown" - may be corrupted
  *          - 1: (deprecated, maps to "unknown")
  *          - 2: "unloaded"
  *          - 3: "loaded"
  *          - 4: "unloading"
  *          - 5: "deleted"
  *          - 6: "loading"
  * @param statusString any of: ["unloaded", "loading", "loaded", "unloading", "deleted", "unknown"] *Only relevant for the MMFiles storage engine*
  * @param type The type of the collection:
  *          - 0: "unknown"
  *          - 2: regular document collection
  *          - 3: edge collection
  * @param waitForSync If *true* then creating, changing or removing
  *        documents will wait until the data has been synchronized to disk.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class CollectionInfo(keyOptions: KeyGeneratorType,
                          doCompact: Option[Boolean] = None,
                          globallyUniqueId: Option[String] = None,
                          id: Option[String] = None,
                          indexBuckets: Option[Int] = None,
                          isSystem: Option[Boolean] = None,
                          isVolatile: Option[Boolean] = None,
                          journalSize: Option[Int] = None,
                          name: Option[String] = None,
                          numberOfShards: Option[Int] = None,
                          replicationFactor: Option[Int] = None,
                          shardKeys: Option[List[String]] = None,
                          shardingStrategy: Option[String] = None,
                          smartGraphAttribute: Option[String] = None,
                          status: Option[String] = None,
                          statusString: Option[String] = None,
                          `type`: Option[Int] = None,
                          waitForSync: Option[Boolean] = None)