package com.outr.arango.api

/**
  * GeneralGraphEdgeDefinitionModifyHttpExamples
  *
  * @param collection The name of the edge collection to be used.
  * @param from One or many vertex collections that can contain source vertices.
  * @param to One or many vertex collections that can contain target vertices.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GeneralGraphEdgeDefinitionModifyHttpExamples(collection: String,
                                                        from: Option[List[String]] = None,
                                                        to: Option[List[String]] = None)