package com.outr.arango.api

/**
  * GeneralGraphListEdgeHttpExamplesRc200
  *
  * @param error Flag if there was an error (true) or not (false).
  *        It is false in this response.
  * @param code The response code.
  * @param collections The list of all vertex collections within this graph.
  *        Includes collections in edgeDefinitions as well as orphans.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GeneralGraphListEdgeHttpExamplesRc200(error: Boolean,
                                                 code: Option[Int] = None,
                                                 collections: Option[List[String]] = None)