package com.outr.arango.api

/**
  * GeneralGraphCreateHttpExamples
  *
  * @param name Name of the graph.
  * @param edgeDefinitions *** No description ***
  * @param isSmart Define if the created graph should be smart.
  *        This only has effect in Enterprise Edition.
  * @param options *** No description ***
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GeneralGraphCreateHttpExamples(name: String,
                                          edgeDefinitions: Option[GraphEdgeDefinition] = None,
                                          isSmart: Option[Boolean] = None,
                                          options: Option[PostAPIGharialCreateOpts] = None)