package com.outr.arango.api

/**
  * GetAPIReturnRc200
  *
  * @param server will always contain *arango*
  * @param details *** No description ***
  * @param version the server version string. The string has the format
  *        "*major*.*minor*.*sub*". *major* and *minor* will be numeric, and *sub*
  *        may contain a number or a textual version.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GetAPIReturnRc200(server: String,
                             details: Option[VersionDetailsStruct] = None,
                             version: Option[String] = None)