package com.outr.arango.api

/**
  * GraphList
  *
  * @param graph *** No description ***
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GraphList(graph: Option[GraphRepresentation] = None)