package com.outr.arango.api

/**
  * PostAPINewTasksRc200
  *
  * @param id A string identifying the task
  * @param code The status code, 200 in this case.
  * @param command the javascript function for this task
  * @param created The timestamp when this task was created
  * @param database the database this task belongs to
  * @param error *false* in this case
  * @param offset time offset in seconds from the created timestamp
  * @param period this task should run each `period` seconds
  * @param type What type of task is this [ `periodic`, `timed`]
  *         - periodic are tasks that repeat periodically
  *         - timed are tasks that execute once at a specific time
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostAPINewTasksRc200(id: String,
                                code: Option[Double] = None,
                                command: Option[String] = None,
                                created: Option[Double] = None,
                                database: Option[String] = None,
                                error: Option[Boolean] = None,
                                offset: Option[Double] = None,
                                period: Option[Double] = None,
                                `type`: Option[String] = None)