package com.outr.arango.api

/**
  * PostAPIViewIresearch
  *
  * @param name The name of the view.
  * @param properties *** No description ***
  * @param type The type of the view. must be equal to *"arangosearch"*
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostAPIViewIresearch(name: String,
                                properties: Option[PostAPIViewProps] = None,
                                `type`: Option[String] = None)