package com.outr.arango.api

/**
  * PostAPIExplain
  *
  * @param query the query which you want explained; If the query references any bind variables,
  *        these must also be passed in the attribute *bindVars*. Additional
  *        options for the query can be passed in the *options* attribute.
  * @param bindVars key/value pairs representing the bind parameters.
  * @param options *** No description ***
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostAPIExplain(query: String,
                          bindVars: Option[List[String]] = None,
                          options: Option[ExplainOptions] = None)