package com.outr.arango.api

/**
  * PostAdminEchoRc200
  *
  * @param authorized whether the session is authorized
  * @param client *** No description ***
  * @param cookies list of the cookies you sent
  * @param database the database this request was executed on
  * @param headers the list of the HTTP headers you sent
  * @param internals contents of the server internals struct
  * @param parameters Object containing the query parameters
  * @param path relative path of this request
  * @param prefix prefix of the database
  * @param protocol the transport, one of ['http', 'https', 'velocystream']
  * @param rawRequestBody List of digits of the sent characters
  * @param rawSuffix *** No description ***
  * @param requestBody stringified version of the POST body we sent
  * @param requestType In this case *POST*, if you use another HTTP-Verb, you will se that (GET/DELETE, ...)
  * @param server *** No description ***
  * @param suffix *** No description ***
  * @param url the raw request URL
  * @param user the currently user that sent this request
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostAdminEchoRc200(authorized: Boolean,
                              client: Option[AdminEchoClientStruct] = None,
                              cookies: Option[io.circe.Json] = None,
                              database: Option[String] = None,
                              headers: Option[io.circe.Json] = None,
                              internals: Option[io.circe.Json] = None,
                              parameters: Option[io.circe.Json] = None,
                              path: Option[String] = None,
                              prefix: Option[io.circe.Json] = None,
                              protocol: Option[String] = None,
                              rawRequestBody: Option[List[String]] = None,
                              rawSuffix: Option[List[String]] = None,
                              requestBody: Option[String] = None,
                              requestType: Option[String] = None,
                              server: Option[AdminEchoServerStruct] = None,
                              suffix: Option[List[String]] = None,
                              url: Option[String] = None,
                              user: Option[String] = None)