package com.outr.arango.api

/**
  * PostAPIViewFields
  *
  * @param field-name This is a recursive structure for the specific attribute path, potentially
  *        containing any of the following attributes:
  *        *analyzers*, *includeAllFields*, *trackListPositions*, *storeValues*
  *        Any attributes not specified are inherited from the parent.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostAPIViewFields(fieldName: Option[List[io.circe.Json]] = None)