package com.outr.arango.api

/**
  * PostAPIIndexPersistent
  *
  * @param type must be equal to *"persistent"*.
  * @param fields an array of attribute paths.
  * @param sparse if *true*, then create a sparse index.
  * @param unique if *true*, then create a unique index.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostAPIIndexPersistent(`type`: String,
                                  fields: Option[List[String]] = None,
                                  sparse: Option[Boolean] = None,
                                  unique: Option[Boolean] = None)