package com.outr.arango.api

/**
  * PutAPISimpleFulltext
  *
  * @param collection The name of the collection to query.
  * @param attribute The attribute that contains the texts.
  * @param index The identifier of the fulltext-index to use.
  * @param limit The maximal amount of documents to return. The *skip*
  *        is applied before the *limit* restriction. (optional)
  * @param query The fulltext query. Please refer to [Fulltext queries](../../Manual/Appendix/Deprecated/SimpleQueries/FulltextQueries.html)
  *          for details.
  * @param skip The number of documents to skip in the query (optional).
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutAPISimpleFulltext(collection: String,
                                attribute: Option[String] = None,
                                index: Option[String] = None,
                                limit: Option[String] = None,
                                query: Option[String] = None,
                                skip: Option[String] = None)