package com.outr.arango.api

/**
  * PutAPIViewPropertiesIresearch
  *
  * @param properties *** No description ***
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutAPIViewPropertiesIresearch(properties: Option[PostAPIViewProps] = None)