package com.outr.arango.api

/**
  * RestRemoveByKeys
  *
  * @param collection The name of the collection to look in for the documents to remove
  * @param keys array with the _keys of documents to remove.
  * @param options *** No description ***
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class RestRemoveByKeys(collection: String,
                            keys: Option[List[String]] = None,
                            options: Option[PutAPISimpleRemoveByKeysOpts] = None)