package com.outr.arango.api

/**
  * ServerStatisticsStruct
  *
  * @param physicalMemory available physical memory on the server
  * @param threads *** No description ***
  * @param uptime time the server is up and running
  * @param v8Context *** No description ***
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class ServerStatisticsStruct(physicalMemory: Option[Int] = None,
                                  threads: Option[ServerThreadsStruct] = None,
                                  uptime: Option[Int] = None,
                                  v8Context: Option[V8ContextStruct] = None)