package com.outr.arango.api.model

import io.circe.Json

/**
  * AdminStatisticsFiguresStruct
  *
  * @param cuts The distribution vector.
  * @param description A description of the figure.
  * @param group The identifier of the group to which this figure belongs.
  * @param identifier The identifier of the figure. It is unique within the group.
  * @param name The name of the figure.
  * @param type Either {@literal *}current{@literal *}, {@literal *}accumulated{@literal *}, or {@literal *}distribution{@literal *}.
  * @param units Units in which the figure is measured.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class AdminStatisticsFiguresStruct(cuts: Option[String] = None,
                                        description: Option[String] = None,
                                        group: Option[String] = None,
                                        identifier: Option[String] = None,
                                        name: Option[String] = None,
                                        `type`: Option[String] = None,
                                        units: Option[String] = None)