package com.outr.arango.api.model

/**
  * ClusterEndpointsStruct
  *
  * @param endpoint The bind of the coordinator, like `tcp://[::1]:8530`
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class ClusterEndpointsStruct(endpoint: Option[String] = None)