package com.outr.arango.api.model

import io.circe.Json

/**
  * CollectionFiguresJournals
  *
  * @param count The number of journal files.
  * @param fileSize The total filesize of all journal files (in bytes).
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class CollectionFiguresJournals(count: Option[Long] = None,
                                     fileSize: Option[Long] = None)