package com.outr.arango.api.model

import io.circe.Json

/**
  * CollectionFiguresCompactors
  *
  * @param count The number of compactor files.
  * @param fileSize The total filesize of all compactor files (in bytes).
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class CollectionFiguresCompactors(count: Option[Long] = None,
                                       fileSize: Option[Long] = None)