package com.outr.arango.api.model

/**
  * CollectionFiguresRevisions
  *
  * @param count The number of revisions of this collection managed by the storage engine.
  * @param size The memory used for storing the revisions of this collection in the storage 
  *        engine (in bytes). This figure does not include the document data but only mappings 
  *        from document revision ids to storage engine datafile positions.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class CollectionFiguresRevisions(count: Option[Long] = None,
                                      size: Option[Long] = None)