package com.outr.arango.api.model

/**
  * CollectionFiguresDead
  *
  * @param count The number of dead documents. This includes document
  *        versions that have been deleted or replaced by a newer version. Documents
  *        deleted or replaced that are contained the write-ahead log only are not reported
  *        in this figure.
  * @param deletion The total number of deletion markers. Deletion markers
  *        only contained in the write-ahead log are not reporting in this figure.
  * @param size The total size in bytes used by all dead documents.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class CollectionFiguresDead(count: Option[Long] = None,
                                 deletion: Option[Long] = None,
                                 size: Option[Long] = None)