package com.outr.arango.api.model

import io.circe.Json

/**
  * CompactionStatusAttributes
  *
  * @param message The action that was performed when the compaction was last run for the collection. 
  *        This information can be used for debugging compaction issues.
  * @param time The point in time the compaction for the collection was last executed. 
  *        This information can be used for debugging compaction issues.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class CompactionStatusAttributes(message: Option[String] = None,
                                      time: Option[String] = None)