package com.outr.arango.api.model

/**
  * DeleteAPIAqlfunctionRc200
  *
  * @param error boolean flag to indicate whether an error occurred (*false* in this case)
  * @param code the HTTP status code
  * @param deletedCount The number of deleted user functions, always `1` when `group` is set to *false*. 
  *        Any number `>= 0` when `group` is set to *true*
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class DeleteAPIAqlfunctionRc200(error: Boolean,
                                     code: Option[Long] = None,
                                     deletedCount: Option[Long] = None)