package com.outr.arango.api.model

import io.circe.Json

/**
  * DeleteAPITasksRc200
  *
  * @param code The status code, 200 in this case.
  * @param error *false* in this case
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class DeleteAPITasksRc200(code: Double,
                               error: Option[Boolean] = None)