package com.outr.arango.api.model

import io.circe.Json

/**
  * GeneralGraphVertexCreateHttpExamplesRc202
  *
  * @param error Flag if there was an error (true) or not (false).
  *        It is false in this response.
  * @param code The response code.
  * @param new *** No description ***
  * @param vertex *** No description ***
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GeneralGraphVertexCreateHttpExamplesRc202(error: Boolean,
                                                     code: Option[Int] = None,
                                                     `new`: Option[VertexRepresentation] = None,
                                                     vertex: Option[VertexRepresentation] = None)