package com.outr.arango.api.model

/**
  * GeneralGraphVertexGetHttpExamplesRc200
  *
  * @param error Flag if there was an error (true) or not (false).
  *        It is false in this response.
  * @param code The response code.
  * @param vertex *** No description ***
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GeneralGraphVertexGetHttpExamplesRc200(error: Boolean,
                                                  code: Option[Int] = None,
                                                  vertex: Option[VertexRepresentation] = None)