package com.outr.arango.api.model

/**
  * GeneralGraphEdgeReplaceHttpExamples
  *
  * @param _from The source vertex of this edge. Has to be valid within
  *        the used edge definition.
  * @param _to The target vertex of this edge. Has to be valid within
  *        the used edge definition.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GeneralGraphEdgeReplaceHttpExamples(From: String,
                                               To: Option[String] = None)