package com.outr.arango.api.model

import io.circe.Json

/**
  * GetAPIDatabaseNewUSERS
  *
  * @param active A flag indicating whether the user account should be activated or not.
  *        The default value is {@literal *}true{@literal *}. If set to {@literal *}false{@literal *}, the user won't be able to
  *        log into the database.
  * @param extra A JSON object with extra user information. The data contained in {@literal *}extra{@literal *}
  *        will be stored for the user but not be interpreted further by ArangoDB.
  * @param passwd The user password as a string. If not specified, it will default to an empty string.
  * @param username Login name of the user to be created
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GetAPIDatabaseNewUSERS(active: Option[Boolean] = None,
                                  extra: Option[Json] = None,
                                  passwd: Option[String] = None,
                                  username: Option[String] = None)