package com.outr.arango.api.model

import io.circe.Json

/**
  * GetAdminStatisticsDescriptionRc200
  *
  * @param groups *** No description ***
  * @param code the HTTP status code
  * @param error the error, {@literal *}false{@literal *} in this case
  * @param figures *** No description ***
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GetAdminStatisticsDescriptionRc200(groups: AdminStatisticsGroupStruct,
                                              code: Option[Long] = None,
                                              error: Option[Boolean] = None,
                                              figures: Option[AdminStatisticsFiguresStruct] = None)