package com.outr.arango.api.model

import io.circe.Json

/**
  * GetAPIReturnRc200
  *
  * @param server will always contain {@literal *}arango{@literal *}
  * @param details *** No description ***
  * @param version the server version string. The string has the format
  *        "{@literal *}major{@literal *}.{@literal *}minor{@literal *}.{@literal *}sub{@literal *}". {@literal *}major{@literal *} and {@literal *}minor{@literal *} will be numeric, and {@literal *}sub{@literal *}
  *        may contain a number or a textual version.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GetAPIReturnRc200(server: String,
                             details: Option[VersionDetailsStruct] = None,
                             version: Option[String] = None)