package com.outr.arango.api.model

import io.circe.Json

/**
  * GetAdminServerRoleRc200
  *
  * @param error always {@literal *}false{@literal *}
  * @param code the HTTP status code, always 200
  * @param errorNum the server error number
  * @param role one of [ {@literal *}SINGLE{@literal *}, {@literal *}COORDINATOR{@literal *}, {@literal *}PRIMARY{@literal *}, {@literal *}SECONDARY{@literal *}, {@literal *}AGENT{@literal *}, {@literal *}UNDEFINED{@literal *}]
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GetAdminServerRoleRc200(error: Boolean,
                                   code: Option[Long] = None,
                                   errorNum: Option[Long] = None,
                                   role: Option[String] = None)