package com.outr.arango.api.model

/**
  * GetAdminLogRc200
  *
  * @param lid a list of log entry identifiers. Each log message is uniquely
  *        identified by its @LIT{lid} and the identifiers are in ascending
  *        order.
  * @param level A list of the log levels for all log entries.
  * @param text a list of the texts of all log entries
  * @param timestamp a list of the timestamps as seconds since 1970-01-01 for all log
  *        entries.
  * @param topic a list of the topics of all log entries
  * @param totalAmount the total amount of log entries before pagination.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GetAdminLogRc200(lid: List[String],
                            level: Option[String] = None,
                            text: Option[String] = None,
                            timestamp: Option[List[String]] = None,
                            topic: Option[String] = None,
                            totalAmount: Option[Long] = None)