package com.outr.arango.api.model

import io.circe.Json

/**
  * GetAdminStatisticsRc200
  *
  * @param error boolean flag to indicate whether an error occurred (*false* in this case)
  * @param client *** No description ***
  * @param code the HTTP status code - 200 in this case
  * @param enabled *true* if the server has the statistics module enabled. If not, don't expect any values.
  * @param errorMessage a descriptive error message
  * @param http *** No description ***
  * @param server *** No description ***
  * @param system *** No description ***
  * @param time the current server timestamp
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GetAdminStatisticsRc200(error: Boolean,
                                   client: Option[ClientStatisticsStruct] = None,
                                   code: Option[Long] = None,
                                   enabled: Option[Boolean] = None,
                                   errorMessage: Option[String] = None,
                                   http: Option[HttpStatisticsStruct] = None,
                                   server: Option[ServerStatisticsStruct] = None,
                                   system: Option[SystemStatisticsStruct] = None,
                                   time: Option[Long] = None)