package com.outr.arango.api.model

import io.circe.Json

/**
  * GetEngineRc200
  *
  * @param name will be {@literal *}mmfiles{@literal *} or {@literal *}rocksdb{@literal *}
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GetEngineRc200(name: String)