package com.outr.arango.api.model

/**
  * GetEngineRc200
  *
  * @param name will be *mmfiles* or *rocksdb*
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GetEngineRc200(name: String)