package com.outr.arango.api.model

/**
  * GraphEdgeDefinition
  *
  * @param collection Name of the edge collection, where the edge are stored in.
  * @param from List of vertex collection names.
  *        Edges in collection can only be inserted if their _from is in any of the collections here.
  * @param to List of vertex collection names.
  *        Edges in collection can only be inserted if their _to is in any of the collections here.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GraphEdgeDefinition(collection: Option[String] = None,
                               from: Option[List[String]] = None,
                               to: Option[List[String]] = None)