package com.outr.arango.api.model

/**
  * GraphRepresentation
  *
  * @param _id The internal id value of this graph.
  * @param _rev The revision of this graph. Can be used to make sure to not override
  *        concurrent modifications to this graph.
  * @param edgeDefinitions *** No description ***
  * @param isSmart Flag if the graph is a SmartGraph (Enterprise Edition only) or not.
  * @param name The name of the graph.
  * @param numberOfShards Number of shards created for every new collection in the graph.
  * @param orphanCollections An array of additional vertex collections.
  *        Documents within these collections do not have edges within this graph.
  * @param replicationFactor The replication factor used for every new collection in the graph.
  * @param smartGraphAttribute The name of the sharding attribute in smart graph case (Enterprise Edition only)
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class GraphRepresentation(Id: Option[String] = None,
                               Rev: Option[String] = None,
                               edgeDefinitions: Option[GraphEdgeDefinition] = None,
                               isSmart: Option[Boolean] = None,
                               name: Option[String] = None,
                               numberOfShards: Option[Int] = None,
                               orphanCollections: Option[List[String]] = None,
                               replicationFactor: Option[Int] = None,
                               smartGraphAttribute: Option[String] = None)