package com.outr.arango.api.model

/**
  * HttpStatisticsStruct
  *
  * @param requestsAsync total number of asynchronous http requests
  * @param requestsDelete No of requests using the DELETE-verb
  * @param requestsGet No of requests using the GET-verb
  * @param requestsHead No of requests using the HEAD-verb
  * @param requestsOptions No of requests using the OPTIONS-verb
  * @param requestsOther No of requests using the none of the above identified verbs
  * @param requestsPatch No of requests using the PATCH-verb
  * @param requestsPost No of requests using the POST-verb
  * @param requestsPut No of requests using the PUT-verb
  * @param requestsTotal total number of http requests
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class HttpStatisticsStruct(requestsAsync: Option[Int] = None,
                                requestsDelete: Option[Int] = None,
                                requestsGet: Option[Int] = None,
                                requestsHead: Option[Int] = None,
                                requestsOptions: Option[Int] = None,
                                requestsOther: Option[Int] = None,
                                requestsPatch: Option[Int] = None,
                                requestsPost: Option[Int] = None,
                                requestsPut: Option[Int] = None,
                                requestsTotal: Option[Int] = None)