package com.outr.arango.api.model

import io.circe.Json

/**
  * KeyGeneratorType
  *
  * @param allowUserKeys if set to {@literal *}true{@literal *}, then it is allowed to supply
  *        own key values in the {@literal *}_key{@literal *} attribute of a document. If set to
  *        {@literal *}false{@literal *}, then the key generator is solely responsible for
  *        generating keys and supplying own key values in the {@literal *}_key{@literal *} attribute
  *        of documents is considered an error.
  * @param lastValue *** No description ***
  * @param type specifies the type of the key generator. The currently
  *        available generators are {@literal *}traditional{@literal *}, {@literal *}autoincrement{@literal *}, {@literal *}uuid{@literal *}
  *        and {@literal *}padded{@literal *}.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class KeyGeneratorType(allowUserKeys: Option[Boolean] = None,
                            lastValue: Option[Int] = None,
                            `type`: Option[String] = None)