package com.outr.arango.api.model

/**
  * PostAPIViewLinks
  *
  * @param [collection-name] *** No description ***
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostAPIViewLinks(collectionName: Option[PostAPIViewLinkProps] = None)