package com.outr.arango.api.model

/**
  * PostAPIViewPropsConsolidation
  *
  * 
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostAPIViewPropsConsolidation()