package com.outr.arango.api.model

/**
  * PostAPIViewLinkProps
  *
  * @param analyzers The list of analyzers to be used for indexing of string values
  *        (default: ["identity"]).
  * @param fields *** No description ***
  * @param includeAllFields The flag determines whether or not to index all fields on a particular level of
  *        depth (default: false).
  * @param storeValues How should the view track the attribute values, this setting allows for
  *        additional value retrieval optimizations, one of:
  *        - *none*: Do not store values by the view
  *        - *id*: Store only information about value presence, to allow use of the EXISTS() function
  *        (default "none").
  * @param trackListPositions The flag determines whether or not values in a lists should be treated separate
  *        (default: false).
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostAPIViewLinkProps(analyzers: Option[List[String]] = None,
                                fields: Option[PostAPIViewFields] = None,
                                includeAllFields: Option[Boolean] = None,
                                storeValues: Option[String] = None,
                                trackListPositions: Option[Boolean] = None)