package com.outr.arango.api.model

import io.circe.Json

/**
  * PostAPIIndexGeo
  *
  * @param type must be equal to {@literal *}"geo"{@literal *}.
  * @param fields An array with one or two attribute paths.
  *        
  *        If it is an array with one attribute path {@literal *}location{@literal *}, then a geo-spatial
  *        index on all documents is created using {@literal *}location{@literal *} as path to the
  *        coordinates. The value of the attribute must be an array with at least two
  *        double values. The array must contain the latitude (first value) and the
  *        longitude (second value). All documents, which do not have the attribute
  *        path or with value that are not suitable, are ignored.
  *        
  *        If it is an array with two attribute paths {@literal *}latitude{@literal *} and {@literal *}longitude{@literal *},
  *        then a geo-spatial index on all documents is created using {@literal *}latitude{@literal *}
  *        and {@literal *}longitude{@literal *} as paths the latitude and the longitude. The value of
  *        the attribute {@literal *}latitude{@literal *} and of the attribute {@literal *}longitude{@literal *} must a
  *        double. All documents, which do not have the attribute paths or which
  *        values are not suitable, are ignored.
  * @param geoJson If a geo-spatial index on a {@literal *}location{@literal *} is constructed
  *        and {@literal *}geoJson{@literal *} is {@literal *}true{@literal *}, then the order within the array is longitude
  *        followed by latitude. This corresponds to the format described in
  *        http://geojson.org/geojson-spec.html#positions
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostAPIIndexGeo(`type`: String,
                           fields: Option[List[String]] = None,
                           geoJson: Option[String] = None)