package com.outr.arango.api.model

/**
  * PostAPIIndexTtl
  *
  * @param type must be equal to *"ttl"*.
  * @param expireAfter The time (in seconds) after a document's creation after which the
  *        documents count as "expired".
  * @param fields an array with exactly one attribute path.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostAPIIndexTtl(`type`: String,
                           expireAfter: Option[Double] = None,
                           fields: Option[List[String]] = None)