package com.outr.arango.api.model

/**
  * PostApiQueryProperties
  *
  * @param query To validate a query string without executing it, the query string can be
  *        passed to the server via an HTTP POST request.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostApiQueryProperties(query: String)