package com.outr.arango.api.model

import io.circe.Json

/**
  * PostAPIIndexFulltext
  *
  * @param type must be equal to *"fulltext"*.
  * @param fields an array of attribute names. Currently, the array is limited
  *        to exactly one attribute.
  * @param minLength Minimum character length of words to index. Will default
  *        to a server-defined value if unspecified. It is thus recommended to set
  *        this value explicitly when creating the index.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostAPIIndexFulltext(`type`: String,
                                fields: Option[List[String]] = None,
                                minLength: Option[Long] = None)