package com.outr.arango.api.model

import io.circe.Json

/**
  * PostAPIViewFields
  *
  * @param field-name This is a recursive structure for the specific attribute path, potentially
  *        containing any of the following attributes:
  *        {@literal *}analyzers{@literal *}, {@literal *}includeAllFields{@literal *}, {@literal *}trackListPositions{@literal *}, {@literal *}storeValues{@literal *}
  *        Any attributes not specified are inherited from the parent.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PostAPIViewFields(fieldName: Option[List[Json]] = None)