package com.outr.arango.api.model

/**
  * PutAPISimpleFirstExample
  *
  * @param collection The name of the collection to query.
  * @param example The example document.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutAPISimpleFirstExample(collection: String,
                                    example: Option[String] = None)