package com.outr.arango.api.model

import io.circe.Json

/**
  * PutAPISimpleRange
  *
  * @param collection The name of the collection to query.
  * @param attribute The attribute path to check.
  * @param closed If {@literal *}true{@literal *}, use interval including {@literal *}left{@literal *} and {@literal *}right{@literal *},
  *        otherwise exclude {@literal *}right{@literal *}, but include {@literal *}left{@literal *}.
  * @param left The lower bound.
  * @param limit The maximal amount of documents to return. The {@literal *}skip{@literal *}
  *        is applied before the {@literal *}limit{@literal *} restriction. (optional)
  * @param right The upper bound.
  * @param skip The number of documents to skip in the query (optional).
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutAPISimpleRange(collection: String,
                             attribute: Option[String] = None,
                             closed: Option[Boolean] = None,
                             left: Option[String] = None,
                             limit: Option[Long] = None,
                             right: Option[String] = None,
                             skip: Option[String] = None)