package com.outr.arango.api.model

/**
  * PutAPISimpleRemoveByKeysOpts
  *
  * @param returnOld if set to *true* and *silent* above is *false*, then the above
  *        information about the removed documents contains the complete
  *        removed documents.
  * @param silent if set to *false*, then the result will contain an additional
  *        attribute *old* which contains an array with one entry for each
  *        removed document. By default, these entries will have the *_id*,
  *        *_key* and *_rev* attributes.
  * @param waitForSync if set to true, then all removal operations will
  *        instantly be synchronized to disk. If this is not specified, then the
  *        collection's default sync behavior will be applied.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutAPISimpleRemoveByKeysOpts(returnOld: Option[Boolean] = None,
                                        silent: Option[Boolean] = None,
                                        waitForSync: Option[Boolean] = None)