package com.outr.arango.api.model

import io.circe.Json

/**
  * PutAPISimpleUpdateByExampleOptions
  *
  * @param keepNull This parameter can be used to modify the behavior when
  *        handling {@literal *}null{@literal *} values. Normally, {@literal *}null{@literal *} values are stored in the
  *        database. By setting the {@literal *}keepNull{@literal *} parameter to {@literal *}false{@literal *}, this
  *        behavior can be changed so that all attributes in {@literal *}data{@literal *} with {@literal *}null{@literal *}
  *        values will be removed from the updated document.
  * @param limit an optional value that determines how many documents to
  *        update at most. If {@literal *}limit{@literal *} is specified but is less than the number
  *        of documents in the collection, it is undefined which of the documents
  *        will be updated.
  * @param mergeObjects Controls whether objects (not arrays) will be merged if present in both the
  *        existing and the patch document. If set to false, the value in the
  *        patch document will overwrite the existing document's value. If set to
  *        true, objects will be merged. The default is true.
  * @param waitForSync if set to true, then all removal operations will
  *        instantly be synchronized to disk. If this is not specified, then the
  *        collection's default sync behavior will be applied.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutAPISimpleUpdateByExampleOptions(keepNull: Option[Boolean] = None,
                                              limit: Option[Long] = None,
                                              mergeObjects: Option[Boolean] = None,
                                              waitForSync: Option[Boolean] = None)