package com.outr.arango.api.model

import io.circe.Json

/**
  * PutAPISimpleWithin
  *
  * @param collection The name of the collection to query.
  * @param distance If given, the attribute key used to return the distance to
  *        the given coordinate. (optional). If specified, distances are returned in meters.
  * @param geo If given, the identifier of the geo-index to use. (optional)
  * @param latitude The latitude of the coordinate.
  * @param limit The maximal amount of documents to return. The {@literal *}skip{@literal *} is
  *        applied before the {@literal *}limit{@literal *} restriction. The default is 100. (optional)
  * @param longitude The longitude of the coordinate.
  * @param radius The maximal radius (in meters).
  * @param skip The number of documents to skip in the query. (optional)
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutAPISimpleWithin(collection: String,
                              distance: Option[String] = None,
                              geo: Option[String] = None,
                              latitude: Option[String] = None,
                              limit: Option[String] = None,
                              longitude: Option[String] = None,
                              radius: Option[String] = None,
                              skip: Option[String] = None)