package com.outr.arango.api.model

import io.circe.Json

/**
  * PutAPISimpleAny
  *
  * @param collection The identifier or name of the collection to query.
  *        
  *        Returns a JSON object with the document stored in the attribute
  *        {@literal *}document{@literal *} if the collection contains at least one document. If
  *        the collection is empty, the {@literal *}document{@literal *} attribute contains null.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutAPISimpleAny(collection: String)