package com.outr.arango.api.model

import io.circe.Json

/**
  * PutAPISimpleRemoveByExample
  *
  * @param collection The name of the collection to remove from.
  * @param example An example document that all collection documents are compared against.
  * @param options *** No description ***
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutAPISimpleRemoveByExample(collection: String,
                                       example: Option[String] = None,
                                       options: Option[PutAPISimpleRemoveByExampleOpts] = None)