package com.outr.arango.api.model

import io.circe.Json

/**
  * PutAPISimpleUpdateByExample
  *
  * @param collection The name of the collection to update within.
  * @param example An example document that all collection documents are compared against.
  * @param newValue A document containing all the attributes to update in the found documents.
  * @param options *** No description ***
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutAPISimpleUpdateByExample(collection: String,
                                       example: Option[String] = None,
                                       newValue: Option[Json] = None,
                                       options: Option[PutAPISimpleUpdateByExampleOptions] = None)