package com.outr.arango.api.model

/**
  * PutAdminLoglevel
  *
  * @param agency One of the possible log levels.
  * @param agencycomm One of the possible log levels.
  * @param audit-authentication One of the possible log levels.
  * @param audit-authorization One of the possible log levels.
  * @param audit-collection One of the possible log levels.
  * @param audit-database One of the possible log levels.
  * @param audit-document One of the possible log levels.
  * @param audit-service One of the possible log levels.
  * @param audit-view One of the possible log levels.
  * @param authentication One of the possible log levels.
  * @param authorization One of the possible log levels.
  * @param cache One of the possible log levels.
  * @param cluster One of the possible log levels.
  * @param collector One of the possible log levels.
  * @param communication One of the possible log levels.
  * @param compactor One of the possible log levels.
  * @param config One of the possible log levels.
  * @param datafiles One of the possible log levels.
  * @param development One of the possible log levels.
  * @param engines One of the possible log levels.
  * @param general One of the possible log levels.
  * @param graphs One of the possible log levels.
  * @param heartbeat One of the possible log levels.
  * @param ldap One of the possible log levels.
  * @param memory One of the possible log levels.
  * @param mmap One of the possible log levels.
  * @param performance One of the possible log levels.
  * @param pregel One of the possible log levels.
  * @param queries One of the possible log levels.
  * @param replication One of the possible log levels.
  * @param requests One of the possible log levels.
  * @param rocksdb One of the possible log levels.
  * @param ssl One of the possible log levels.
  * @param startup One of the possible log levels.
  * @param supervision One of the possible log levels.
  * @param syscall One of the possible log levels.
  * @param threads One of the possible log levels.
  * @param trx One of the possible log levels.
  * @param v8 One of the possible log levels.
  * @param views One of the possible log levels.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutAdminLoglevel(agency: Option[String] = None,
                            agencycomm: Option[String] = None,
                            auditAuthentication: Option[String] = None,
                            auditAuthorization: Option[String] = None,
                            auditCollection: Option[String] = None,
                            auditDatabase: Option[String] = None,
                            auditDocument: Option[String] = None,
                            auditService: Option[String] = None,
                            auditView: Option[String] = None,
                            authentication: Option[String] = None,
                            authorization: Option[String] = None,
                            cache: Option[String] = None,
                            cluster: Option[String] = None,
                            collector: Option[String] = None,
                            communication: Option[String] = None,
                            compactor: Option[String] = None,
                            config: Option[String] = None,
                            datafiles: Option[String] = None,
                            development: Option[String] = None,
                            engines: Option[String] = None,
                            general: Option[String] = None,
                            graphs: Option[String] = None,
                            heartbeat: Option[String] = None,
                            ldap: Option[String] = None,
                            memory: Option[String] = None,
                            mmap: Option[String] = None,
                            performance: Option[String] = None,
                            pregel: Option[String] = None,
                            queries: Option[String] = None,
                            replication: Option[String] = None,
                            requests: Option[String] = None,
                            rocksdb: Option[String] = None,
                            ssl: Option[String] = None,
                            startup: Option[String] = None,
                            supervision: Option[String] = None,
                            syscall: Option[String] = None,
                            threads: Option[String] = None,
                            trx: Option[String] = None,
                            v8: Option[String] = None,
                            views: Option[String] = None)