package com.outr.arango.api.model

import io.circe.Json

/**
  * PutAdminServerMode
  *
  * @param mode The mode of the server `readonly` or `default`.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutAdminServerMode(mode: String)