package com.outr.arango.api.model

import io.circe.Json

/**
  * PutAPIReplicationSynchronize
  *
  * @param endpoint the master endpoint to connect to (e.g. "tcp://192.168.173.13:8529").
  * @param database the database name on the master (if not specified, defaults to the
  *        name of the local current database).
  * @param includeSystem whether or not system collection operations will be applied
  * @param incremental if set to {@literal *}true{@literal *}, then an incremental synchronization method will be used
  *        for synchronizing data in collections. This method is useful when
  *        collections already exist locally, and only the remaining differences need
  *        to be transferred from the remote endpoint. In this case, the incremental
  *        synchronization can be faster than a full synchronization.
  *        The default value is {@literal *}false{@literal *}, meaning that the complete data from the remote
  *        collection will be transferred.
  * @param initialSyncMaxWaitTime the maximum wait time (in seconds) that the initial synchronization will
  *        wait for a response from the master when fetching initial collection data.
  *        This wait time can be used to control after what time the initial synchronization
  *        will give up waiting for a response and fail.
  *        This value will be ignored if set to {@literal *}0{@literal *}.
  * @param password the password to use when connecting to the endpoint.
  * @param restrictCollections an optional array of collections for use with
  *        {@literal *}restrictType{@literal *}. If {@literal *}restrictType{@literal *} is {@literal *}include{@literal *}, only the specified collections
  *        will be sychronised. If {@literal *}restrictType{@literal *} is {@literal *}exclude{@literal *}, all but the specified
  *        collections will be synchronized.
  * @param restrictType an optional string value for collection filtering. When
  *        specified, the allowed values are {@literal *}include{@literal *} or {@literal *}exclude{@literal *}.
  * @param username an optional ArangoDB username to use when connecting to the endpoint.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutAPIReplicationSynchronize(endpoint: String,
                                        database: Option[String] = None,
                                        includeSystem: Option[Boolean] = None,
                                        incremental: Option[Boolean] = None,
                                        initialSyncMaxWaitTime: Option[Long] = None,
                                        password: Option[String] = None,
                                        restrictCollections: Option[List[String]] = None,
                                        restrictType: Option[String] = None,
                                        username: Option[String] = None)