package com.outr.arango.api.model

/**
  * PutAPISimpleByExample
  *
  * @param collection The name of the collection to query.
  * @param batchSize maximum number of result documents to be transferred from
  *        the server to the client in one roundtrip. If this attribute is
  *        not set, a server-controlled default value will be used. A *batchSize* value of
  *        *0* is disallowed.
  * @param example The example document.
  * @param limit The maximal amount of documents to return. The *skip*
  *        is applied before the *limit* restriction. (optional)
  * @param skip The number of documents to skip in the query (optional).
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutAPISimpleByExample(collection: String,
                                 batchSize: Option[Long] = None,
                                 example: Option[String] = None,
                                 limit: Option[String] = None,
                                 skip: Option[String] = None)