package com.outr.arango.api.model

/**
  * PutBatchReplication
  *
  * @param ttl the time-to-live for the new batch (in seconds)
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutBatchReplication(ttl: Long)