package com.outr.arango.api.model

/**
  * PutReadAllDocuments
  *
  * @param collection The collection that should be queried
  * @param type The type of the result. The following values are allowed:
  *        
  *          - *id*: returns an array of document ids (*_id* attributes)
  *          - *key*: returns an array of document keys (*_key* attributes)
  *          - *path*: returns an array of document URI paths. This is the default.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutReadAllDocuments(collection: String,
                               `type`: Option[String] = None)