package com.outr.arango.api.model

import io.circe.Json

/**
  * PutReadAllDocuments
  *
  * @param collection The collection that should be queried
  * @param type The type of the result. The following values are allowed:
  *        
  *          - {@literal *}id{@literal *}: returns an array of document ids ({@literal *}_id{@literal *} attributes)
  *          - {@literal *}key{@literal *}: returns an array of document keys ({@literal *}_key{@literal *} attributes)
  *          - {@literal *}path{@literal *}: returns an array of document URI paths. This is the default.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class PutReadAllDocuments(collection: String,
                               `type`: Option[String] = None)