package com.outr.arango.api.model

/**
  * ServerThreadsStruct
  *
  * @param in-progress The number of currently busy worker threads
  * @param queued The number of jobs queued up waiting for worker threads becomming available
  * @param scheduler-threads The number of spawned worker threads
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class ServerThreadsStruct(inProgress: Option[Int] = None,
                               queued: Option[Int] = None,
                               schedulerThreads: Option[Int] = None)