package com.outr.arango.api.model

import io.circe.Json

/**
  * SystemStatisticsStruct
  *
  * @param majorPageFaults pagefaults
  * @param minorPageFaults pagefaults
  * @param numberOfThreads the number of threads in the server
  * @param residentSize RSS of process
  * @param residentSizePercent RSS of process in %
  * @param systemTime the system CPU time used by the server process
  * @param userTime the user CPU time used by the server process
  * @param virtualSize VSS of the process
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class SystemStatisticsStruct(majorPageFaults: Option[Int] = None,
                                  minorPageFaults: Option[Int] = None,
                                  numberOfThreads: Option[Int] = None,
                                  residentSize: Option[Int] = None,
                                  residentSizePercent: Option[Double] = None,
                                  systemTime: Option[Double] = None,
                                  userTime: Option[Double] = None,
                                  virtualSize: Option[Int] = None)