package com.outr.arango.api.model

import io.circe.Json

/**
  * UserHandlingGrantCollection
  *
  * @param grant Use "rw" to set the collection level access to *Read/Write*.
  *        
  *        Use "ro" to set the collection level access to  *Read Only*.
  *        
  *        Use "none" to set the collection level access to *No access*.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class UserHandlingGrantCollection(grant: String)