package com.outr.arango.api.model

import io.circe.Json

/**
  * UserHandlingGrantDatabase
  *
  * @param grant Use "rw" to set the database access level to {@literal *}Administrate{@literal *} .
  *        
  *        Use "ro" to set the database access level to {@literal *}Access{@literal *}.
  *        
  *        Use "none" to set the database access level to {@literal *}No access{@literal *}.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class UserHandlingGrantDatabase(grant: String)