package com.outr.arango.api.model

import io.circe.Json

/**
  * UserHandlingGrantCollection
  *
  * @param grant Use "rw" to set the collection level access to {@literal *}Read/Write{@literal *}.
  *        
  *        Use "ro" to set the collection level access to  {@literal *}Read Only{@literal *}.
  *        
  *        Use "none" to set the collection level access to {@literal *}No access{@literal *}.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class UserHandlingGrantCollection(grant: String)