package com.outr.arango.api.model

/**
  * V8ContextStruct
  *
  * @param available the number of currently spawnen V8 contexts
  * @param busy the number of currently active V8 contexts
  * @param dirty the number of contexts that were previously used, and should now be garbage collected before being re-used
  * @param free the number of V8 contexts that are free to use
  * @param max the total number of V8 contexts we may spawn as configured by --javascript.v8-contexts
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class V8ContextStruct(available: Option[Int] = None,
                           busy: Option[Int] = None,
                           dirty: Option[Int] = None,
                           free: Option[Int] = None,
                           max: Option[Int] = None)