package com.outr.arango.api.model

import io.circe.Json

/**
  * VertexRepresentation
  *
  * @param _id The _id value of the stored data.
  * @param _key The _key value of the stored data.
  * @param _rev The _rev value of the stored data.
  *
  * WARNING: This code is generated by youi-plugin's generateHttpClient. Do not modify directly.
  */
case class VertexRepresentation(Id: Option[String] = None,
                                Key: Option[String] = None,
                                Rev: Option[String] = None)